# Generated by Django 5.2.8 on 2026-03-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dadjokes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
    ]
