# Generated by Django 5.2.8 on 2026-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('display_name', models.TextField(blank=True)),
                ('bio_text', models.TextField(blank=True)),
            ],
        ),
    ]
