# Generated by Django 5.2.8 on 2026-04-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlog', '0006_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
