# Generated by Django 5.2.8 on 2026-03-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('residential_address_street_number', models.IntegerField()),
                ('residential_address_street_name', models.TextField()),
                ('residential_address_apartment_number', models.IntegerField()),
                ('residential_address_zip_code', models.IntegerField()),
                ('dob', models.DateField()),
                ('dor', models.DateField()),
                ('party_affiliation', models.CharField(max_length=2)),
                ('precinct_num', models.IntegerField()),
                ('v20state', models.BooleanField()),
                ('v21city', models.BooleanField()),
                ('v21primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
